### ISSUE TITLE
server site bug in 0.5V or might be the client it self ^^

### ISSUE THREAD

**Issue by tiba666** [Longwelwind/Phi#1]
it says 
{
  "type": "auth",
  "name": "|MW|TIBA ???",
  "version": "0.4",
  "hashedKey": "8E4B88632464A57786A3E326C5EE43EC908895A098DA1BAC3557A1AF113EC9FC"
}
even i download the version 0.5 client and server file from here ^^

**Comment by Longwelwind** [comment]
It is an error; I forgot to include the tag changes in the version I've distributed.
