### ISSUE TITLE
Case Insensitive Search

### ISSUE THREAD

**Issue by SimonNguyen** [Longwelwind/Phi#6]
This change will allow you to search for modded items more easily without having to worry about case.

`this.filteredInventory = this.inventory.Where((t) => t.Label.Contains(filterTerm)).ToList();`

Add the StringComparison value OrdinalIgnoreCase to the Contains() method:

`this.filteredInventory = this.inventory.Where((t) => t.Label.Contains(filterTerm, StringComparison.OrdinalIgnoreCase)).ToList();`

**Comment by Longwelwind** [comment]
Fixed, but I wasn't able to do exactly this method.

**Comment by SimonNguyen** [comment]
I wasn't sure if that method would work or not since I couldn't test it. Thanks for the quick turnaroud!
