### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by zDestinate** [Longwelwind/Phi#7]
I try to connect to the server and I keep getting some weird error
I attach the screenshot with the debug log

![rimworld1249win_2016-08-02_04-43-45](https://cloud.githubusercontent.com/assets/1011211/17322534/dd0ac39e-586b-11e6-8cc0-60b47f3b4f6b.png)

**Comment by Longwelwind** [comment]
Do you have the last version of Phi ? (It should say v0.6.3 in the description of Phi in the menu displaying Rimworld's mods)

**Comment by zDestinate** [comment]
It was the server back-end issue. Which forced everyone to disconnected. No idea how did that happened.
It working fine now.
To prevent this from happening again, I think you should check the server XD 

I'm using the latest version too.
